### ISSUE TITLE
don't call home config

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-localhost-utils#3]
where and how could the doorkeeper in this setup be configured to not call home, meaning don't try to check if `id.acdh.oeaw.ac.at` entities already exist in ARCHE?
could you maybe add the needed config.yaml to this repo (I guess here somewhere https://github.com/acdh-oeaw/arche-localhost-utils/tree/master/custom_config)  and adapt the `https://github.com/acdh-oeaw/arche-localhost-utils/blob/master/init-repo.sh` accordingly?

**Comment by zozlak** [comment]
please add:
```
doorkeeper:
  checkRanges: {}
```
to the `custom_config/local.yaml`

**Comment by zozlak** [comment]
As I can see [you are copying](https://github.com/acdh-oeaw/arche-localhost-utils/blob/master/init-repo.sh#L6) this file but you actually **miss it**, please create it with a following content:

```yaml
rest:
    urlBase: http://127.0.0.1
    pathBase: /api/
    # turn off OpenAIRE traffic logging
    handlers:
        methods:
            get: []
            getMetadata: []
doorkeeper:
    epicPid:
        pswd:
    checkRanges: {}
```
